plugins {
    id 'fabric-loom' version '0.10.0'
}

version = '1.0.0'
group = 'com.anarchyclient'

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'com.mojang:minecraft:1.16.5'
    mappings 'net.fabricmc:yarn:1.16.5+build.10:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.11.3'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.42.0+1.16'
}

loom {
    accessWidenerPath = file('src/main/resources/anarchyclient.accesswidener')
}